### PR TITLE
more sensitive html entities for IE

### PR DESCRIPTION
**Pull request by adon-at-work**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
@neraliu , please refer to PPSE-1742 for references when review. thanks.

**Comment by neraliu** [comment]
it looks good, but one thing comes to my mind is that we should extend the *fuzz* project to support different browsers testing from @stuartlarsen

**Comment by adon-at-work** [comment]
Yes. We can explore how to extend that.

**Pull request merged**
