### PR TITLE
Return mapping objects

### PR DESCRIPTION
**Pull request by okuryu**
I think that using conditionals many times are inefficient compared to returning mapping object.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
Thanks for the PR. Seems it's time for speed optimization. :)

We should further avoid constructing the objects repeatedly too. Can simply save them outside the functions for later references. You wanna volunteer for that too? or I can do it tomorrow.

**Comment by okuryu** [comment]
Yup, there is a room for improvement. This is only one small improvement.

I'll try to take a look more details if you can wait this week. I'll leave it up to you if you want to hurry. :)

**Comment by adon-at-work** [comment]
@okuryu, take a look at the following stats:
http://jsperf.com/object-lookup-vs-conditionals-string-as-keys

It seems I should revert the change.

**Comment by okuryu** [comment]
@adon-at-work Interesting, I'll take a look! :)

**Pull request merged**
